### ISSUE TITLE
Support of other calculator

### ISSUE THREAD

**Issue by BeZie** [aiida-phonopy/aiida-phonopy#15]
Dear Atsushi Togo,

Currently only VASP is supported out of the box. 
A support of other main DFT codes would be great (in particular Quantum Espresso) for force calculations but this needs to be included at various points, e.g. in parsing the forces (QE saves them in the output trajectory) and in setting up the calculation.

Best regards,
Benedikt

**Comment by atztogo** [comment]
I don't have enough resource to work on it now.

**Comment by BeZie** [comment]
Thanks for the quick reply.
I have to discuss with my company if I am free to submit code. If so I would be willing to push some changes to support QE.
So far most of my solution is quite brute-forced  and based on catching exceptions.  Is that fine for you or do you plan on  a more structured interface?

Bests,
Benedikt

**Comment by atztogo** [comment]
Then, we should start with the design of the interface. The parameters etc are not carefully chosen (mostly just pushing into Dict), and they are written just to work for me. I am not a user of QE. So the test is difficult. These are issues for me to improve aiida-phonopy. If you want to change aiida-phonopy, I appreciate if you do it little-by-little so that I can review. In addition, emerging DFT codes is also under the development in AiiDA team. So we have to avoid working duplicated stuffs.

**Comment by atztogo** [comment]
I think supporting other calculators are on the way by the work of @bastonero. So I will close this issue. @BeZie, please discuss with @bastonero if you want to know more details.
